Simplify code formatting tests (#431)
* ENH: Update to new flake8 conformance tool

Allow for flake8 with newer pycodestyle and pyflakes versions

Forcing installation of flake8 3.7.9 was incompatiable with newer pycodestyle and pyflakes versions

ERROR: flake8 3.7.9 has requirement pycodestyle<2.6.0,>=2.5.0, but you'll have pycodestyle 2.6.0 which is incompatible.
ERROR: flake8 3.7.9 has requirement pyflakes<2.2.0,>=2.1.0, but you'll have pyflakes 2.2.0 which is incompatible.

* ENH: Add code format checking to test script

Use the test script to also perform code format
testing that must pass for CI to pass.

* Define common requirements-dev.txt for dev packages

Use a commond defintion file to define the devlopment
package dependancies.

* Update pythonapp.yml

Co-authored-by: Wenqi Li <wenqi.li@ucl.ac.uk>